### ISSUE TITLE
Object text in crow.maxhelp disappears when using light or solarized theme

### ISSUE THREAD

**Issue by ngwese** [monome/crow-max#1]
This is minor but could lead to some confusion. In Max 8 when either the `light` or `solarized` UI themes is used the text in the object boxes ends up as black text on black background.

Default theme:
![image](https://user-images.githubusercontent.com/106652/65382577-c3000980-dcbd-11e9-8691-9f6007b5e99d.png)

Light theme:
![image](https://user-images.githubusercontent.com/106652/65382580-c8f5ea80-dcbd-11e9-9246-ca862f035fe4.png)

**Comment by dndrks** [comment]
woah! yeah, seems the theme changes the font color but not the background color? I feel like it should recognize when the colors match/are close by default...

<img width="372" alt="Screen Shot 2019-09-22 at 3 03 04 PM" src="https://user-images.githubusercontent.com/24821020/65393735-46ffd300-dd4a-11e9-8e91-310eb66295b5.png">
<img width="375" alt="Screen Shot 2019-09-22 at 3 03 22 PM" src="https://user-images.githubusercontent.com/24821020/65393738-48c99680-dd4a-11e9-886f-1ddca36b1190.png">

anyway, just pushed a fix (I hope)! confirm success?

**Comment by ngwese** [comment]
yup - looks good on my end as well.

**Comment by ngwese** [comment]
...actually I spoke too soon. The help patchers are good but the crow device selector has a similar problem (light theme example):

![image](https://user-images.githubusercontent.com/106652/65656794-f3091e80-dfd5-11e9-85c9-4c3e2c64b756.png)

**Comment by dndrks** [comment]
great catch!

fixed on my end:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/24821020/65657182-002f0900-dfe8-11e9-9bbf-6768d564dced.png">

pushed change, confirm success?

**Comment by dndrks** [comment]
and caught one in the bootloader patch! geeeez, why wouldn't these just switch out natively?

**Comment by ngwese** [comment]
yeah. Looking good.
