### ISSUE TITLE
super-simple patch to enable bootloader?

### ISSUE THREAD

**Issue by tehn** [monome/crow-max#2]
@dndrks for those not adventurous enough to set up druid, perhaps we should have a super-micro patcher that just activates the bootloader? (`^^b`)

it could have a link to the update docs. or even to github.com/crow/releases/latest (?)

then directs them to run `flash.sh`?

**Comment by dndrks** [comment]
brilliant! i’ll build it out tomorrow AM! it’s in the help patcher, but i
agree it might be really nice to have a really direct way to it :)

**Comment by dndrks** [comment]
done!
https://github.com/monome/crow-max/commit/832d40eaf79dea226e9b4911e860c52fd10f0e60
<img width="258" alt="image" src="https://user-images.githubusercontent.com/24821020/65437440-6b5ebc80-dde9-11e9-930f-2c566f031340.png">
